### PR TITLE
Update to release 7.2

### PR DESCRIPTION
**Pull request by alinelena**
@conda-forge-admin please rerender

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by alinelena** [comment]
yes this seems to be the case. looks like an inconsistent update of the compilers on conda side. I notice in a clean install I have gcc 11.3

**Comment by alinelena** [comment]
@ltalirz something else which is odd my last pipeline seems to pick 12.1 rather than 12.2 like in the error message you posted.
```
-   - package gfortran_linux-64-12.1.0-h7ec3724_10 requires gfortran_impl_linux-64 12.1.0.*, but none of the providers can be installed
```

i tried to fix the compiler versions but somehow still picks the 12 variants.

**Comment by wolfv** [comment]
let me see if we can enable the better error messages in boa and then we would have more informative output. I suspect that some of the dependencies need to be rebuilt for the latest compilers. cc @AntoinePrv

**Comment by unkcpz** [comment]
Superseded by #40. @alinelena I hope you don't mind.

I think the reason for pinning compiler was not working, is that you make a commit after the conda forge render, which will not automatically update things from `recipe/meta.yaml`. The tip is to not pull after the render bot makes the commit but always force push and then trigger the render.

**Comment by ltalirz** [comment]
#40 has been merged

**Pull request closed without merging**
