### PR TITLE
enable ELPA support

### PR DESCRIPTION
**Pull request by Chronum94**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

1. The QE release source has been changed to Gitlab.
2. Elpa support has been added to the build.
3. CMake requirement updated to >=3.18.0 since [it's a recommended prerequisite?](https://gitlab.com/QEF/q-e/-/wikis/Developers/CMake-build-system)

Can we add LibXC support too for the Linux case? It appears they build Fortran bindings in [Linux](https://github.com/conda-forge/libxc-feedstock/blob/a2bd16a10029b20d5a262879ddfcef652464c7d1/recipe/build.sh) now.

The unchecked checkboxes up top have been left alone since I can't intelligently decide on what is the correct choice.

### CODE REVIEW

**Comment by Chronum94** [comment]
@jan-janssen All but one test seems to be passing, so maybe this can get a review?

**Comment by ltalirz** [comment]
Hi @Chronum94 , thanks for the contribution!

It seems to me that the linux build fails because it does not find `average.x` anymore (not entirely sure?).
Could you check whether that binary does no longer exist in 7.1?
If not, then the corresponding check can be removed.

That the build on osx is timing out seems a bit more worrying, I guess this has to do with the introduction of ELPA.

Also, the test suite on Linux seems to take significantly longer now (2800s vs 1800s before - this can also depend on the runner but it would warrant some benchmark).

**Review by ltalirz — APPROVED** [review]
Looks to me like test runs no longer are slow (not sure how much variation there is in available VCPU on the runners anyhow).

On Linux, 1 tests fails (as on current master); and on MacOS 6 tests fail (vs 8 on current master).

From my side this is fine - what about @jan-janssen ?

**Comment by Chronum94** [comment]
Would this be a good opportunity to enable a few more add-ons? I had pw2qmcpack in mind. https://github.com/QMCPACK/pw2qmcpack Suggests that it's just a change to the CMake build line.

**Comment by ltalirz** [comment]
I suggest you open a separate PR for this once we've merged this one

**Comment by jan-janssen** [comment]
> From my side this is fine - what about @jan-janssen ?

I am sorry for the delay - yes looks good to me. Merged it.

**Pull request merged**
