### PR TITLE
try running test suite

### LINKED ISSUE #14: consider running test suite
It seems to me that the builds are currently untested (?)

### PR DESCRIPTION
**Pull request by ltalirz**
fix #14 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@jan-janssen now [running test suite](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=308902&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=8140)

it's only 17 tests, and not all executables are tested but I guess it's a good start

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@ltalirz thanks a lot

**Comment by jan-janssen** [comment]
@ltalirz By the way if you want to add yourself as a maintainer feel free to do so.

**Pull request merged**
