### PR TITLE
Build for linux_aarch64

### LINKED ISSUE #33: Build for ARM architecture (linux-aarch64, mac-arm64)
### Comment:

Hey all,

Essentially, I would like to allow for people on Apple M chips to use QE (and @jan-janssen this extends to all of the quantum codes).

There's two ways: (1) directly via `conda install`, (2) via a docker container which has e.g. [Mambaforge-Linux-aarch64](https://github.com/conda-forge/miniforge) installed.

Is this possible?

Here's some instructions: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/, 
and also I note, you can run e.g. `CONDA_SUBDIR=linux-aarch64 conda create -n test qe`, to check if a package is available for a particular architecture.

### PR DESCRIPTION
**Pull request by chrisjsewell**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #33

### CODE REVIEW

**Comment by chrisjsewell** [comment]
@conda-forge-admin, please rerender

**Comment by chrisjsewell** [comment]
@conda-forge-admin, please rerender

**Comment by chrisjsewell** [comment]
@conda-forge-admin, please rerender

**Comment by chrisjsewell** [comment]
@conda-forge-admin, please rerender

**Comment by unkcpz** [comment]
Hi @chrisjsewell, any issue blocking this?

**Comment by chrisjsewell** [comment]
> Hi @chrisjsewell, any issue blocking this? 

Yep, as you can see, for some reason the code is compiling incredibly slow, and then times out at 6 hours.

I'm not sure if this is because (a) there is some inherent reason why QE would build slow on this architecture (perhaps someone can try manually) or (b) it is something to do with the build environment provided by azure (perhaps ask the conda-forge admin for advice)

**Comment by unkcpz** [comment]
Okay, thanks! Can you reopen this and render the build again? I want to have a look at the build log and see if I can help or see how to proceed.

**Comment by ltalirz** [comment]
I don't know exactly how the linux-aarch64 build process works but if it is cross-compiling https://github.com/conda-forge/conda-forge.github.io/issues/932 it is possible that it simply is very slow

**Comment by unkcpz** [comment]
@ltalirz thanks! From the log, the compilation was finished and it was canceled at the test phase https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=681735&view=logs&j=6494c7a6-a019-59a3-6f3d-9bab8ca96717&t=47f1ac7e-d0be-5d8d-6da0-bd921ed9abfb. However, seems except for the self-hosted runner, the maximum timeout sadly is 6 hours: https://go.microsoft.com/fwlink/?linkid=2077134 😢

**Comment by ltalirz** [comment]
you could limit the test suite for aarch builds

**Comment by chrisjsewell** [comment]
>  but if it is cross-compiling
> the maximum timeout sadly is 6 hours

yeh there seems to be something weird going on, I would hope maybe there is some solution (change of configuration or something) that would make it run a lot faster than 6 hours 😅
Perhaps someone else has encountered this issue for another conda-forge package?

**Comment by unkcpz** [comment]
🎉 disable the test for aarch64 works, see #34

**Pull request closed without merging**
