### PR TITLE
QE 7.2 bump

### PR DESCRIPTION
**Pull request by unkcpz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Based on https://github.com/conda-forge/qe-feedstock/pull/38 try to pin the compiler version again.

### CODE REVIEW

**Comment by unkcpz** [comment]
@conda-forge-admin, please rerender

**Comment by unkcpz** [comment]
@conda-forge-admin, please rerender

**Review by ltalirz — APPROVED** [review]
thanks @unkcpz, this looks good to me

**Comment by ltalirz** [comment]
Test result linux
```
Total Test time (real) = 2080.94 sec

The following tests FAILED:
	211 - system--pw_relax-correctness (Failed)
	317 - system--pw_workflow_vc-relax_scf-correctness (Failed)
```

Test result macos
```
Total Test time (real) = 2474.92 sec

The following tests FAILED:
	 35 - test_qe_lapack_zdotc (Failed)
	165 - system--pw_metaGGA-correctness (Failed)
	211 - system--pw_relax-correctness (Failed)
	219 - system--pw_scf-correctness (Failed)
	297 - system--pw_workflow_exx_nscf-correctness (Failed)
	317 - system--pw_workflow_vc-relax_scf-correctness (Failed)
```

**Pull request merged**
