### PR TITLE
add osx support

### PR DESCRIPTION
**Pull request by ltalirz**
Looking into what would be necessary for osx support

fix https://github.com/conda-forge/qe-feedstock/issues/17

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
I think you might have to rerender to enable OS X CI?

@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
thanks! yes, I'd done that but in the rebase I removed the commit to avoid conflicts - thanks for putting it back :-)

**Comment by ltalirz** [comment]
hmmm, the build errors at linking `libpw.a` because the fft libs are not found
```
libpw.a
mpif90 -fopenmp -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -o pw.x \
   pwscf.o  libpw.a ../../Modules/libqemod.a ../../KS_Solvers/libks_solvers.a ../../upflib/libupf.a ../../FFTXlib/libqefft.a ../../LAXlib/libqela.a ../../UtilXlib/libutil.a ../../dft-d3/libdftd3qe.a $SRC_DIR//clib/clib.a $SRC_DIR//LIBBEEF/libbeef.a    -L$PREFIX/lib -llapack -L$SRC_DIR//FoX/lib  -lFoX_dom -lFoX_sax -lFoX_wxml -lFoX_common -lFoX_utils -lFoX_fsys   -L$PREFIX/lib -lblas   
mpif90 -fopenmp -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -o pw.x \
   pwscf.o  libpw.a ../../Modules/libqemod.a ../../KS_Solvers/libks_solvers.a ../../upflib/libupf.a ../../FFTXlib/libqefft.a ../../LAXlib/libqela.a ../../UtilXlib/libutil.a ../../dft-d3/libdftd3qe.a $SRC_DIR//clib/clib.a $SRC_DIR//LIBBEEF/libbeef.a    -L$PREFIX/lib -llapack -L$SRC_DIR//FoX/lib  -lFoX_dom -lFoX_sax -lFoX_wxml -lFoX_common -lFoX_utils -lFoX_fsys   -L$PREFIX/lib -lblas   
```
and indeed there is no `-lfftw` in this link line... I'll check the configure output

**Comment by ltalirz** [comment]
@jan-janssen @wolfv looks like we have a MacOS version - please review :-)

Also fixes #17 

Please "squash" this one - no need to pollute the commit log.

**Comment by ltalirz** [comment]
P.S. To start a good practice:

linux configure output
```
The following libraries have been found:
  BLAS_LIBS=-lblas
  LAPACK_LIBS=-llapack
  SCALAPACK_LIBS=-lscalapack
  FFT_LIBS=-lfftw3_omp -lfftw3 -lm
  
  

Please check if this is what you expect.

If any libraries are missing, you may specify a list of directories
to search and retry, as follows:
  ./configure LIBDIRS="list of directories, separated by spaces"

Parallel environment detected successfully.\
Configured for compilation of parallel executables.
```

macos configure output
```
The following libraries have been found:
  BLAS_LIBS=-lblas
  LAPACK_LIBS=-llapack
  SCALAPACK_LIBS=-lscalapack
  FFT_LIBS=-lfftw3_omp -lfftw3 -lm
  
  

Please check if this is what you expect.

If any libraries are missing, you may specify a list of directories
to search and retry, as follows:
  ./configure LIBDIRS="list of directories, separated by spaces"

Parallel environment detected successfully.\
Configured for compilation of parallel executables.
```

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
> @jan-janssen @wolfv looks like we have a MacOS version - please review :-)
> 
> Also fixes #17
> 
> Please "squash" this one - no need to pollute the commit log.

Thanks a lot - great work - looks fine to me.

**Pull request merged**
